name: Reusable workflow

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.example_job.outputs.output1 }}
      

jobs:
  example_job:
    name: Generate output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      output1: ${{ steps.step1.outputs.ACCESSID }}
      
    steps:
      - id: step1
        run: echo "ACCESSID=${{ secrets.ACCESS_ID }}" >> $GITHUB_OUTPUT
        
     
  
